sd_app/urls.py
# URL mappings for the application
from django.urls import path
from . import views

# Define the namespace for the sd_app.
app_name = "sd_app"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('profile/', views.profilePage, name = 'profile'),
    path('buy/', views.buyPage, name='buy'),
    path("register/", views.registerPage, name="register"),
    path('purchase_history/', views.purchaseHistoryPage, name='purchase_history'),

    ]

sd_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sd_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

sd_app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinLengthValidator
import datetime


class Transaction(models.Model):
    """
    Transaction model
    """        
    # Amount being purchased
    number_of_people = models.IntegerField()
    # Date and time of desired delivery
    reservation_date = models.CharField(max_length=15)
    reservation_time = models.CharField(max_length=100, default='')
    user_phone_number = models.CharField(max_length=100, default='')
    user_email = models.CharField(max_length=100, default='')
    preferred_payment_method = models.CharField(max_length=100, default='')

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    address_1 = models.CharField(max_length=100, default='')
    address_2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, default='')
    state = models.CharField(max_length=2, default='')
    zipcode = models.CharField(max_length=9, validators=[MinLengthValidator(5)], default='')

    def __str__(self):
        return "Number of people: " + str(self.number_of_people) + ". Delivery Date: " + str(self.reservation_date)

STATE_CHOICES = (
    ('al','AL'),
    ('ak','AK'),
    ('az','AZ'),
    ('ar','AR'),
    ('ca','CA'),
    ('co','CO'),
    ('ct','CT'),
    ('de','DE'),
    ('fl','FL'),
    ('ga','GA'),
    ('hi','HI'),
    ('id','ID'),
    ('il','IL'),
    ('in','IN'),
    ('ia','IA'),
    ('ks','KS'),
    ('ky','KY'),
    ('la','LA'),
    ('me','ME'),
    ('md','MD'),
    ('ma','MA'),
    ('mi','MI'),
    ('mn','MN'),
    ('ms','MS'),
    ('mo','MO'),
    ('mt','MT'),
    ('ne','NE'),
    ('nv','NV'),
    ('nh','NH'),
    ('nj','NJ'),
    ('nm','NM'),
    ('ny','NY'),
    ('nc','NC'),
    ('nd','ND'),
    ('oh','OH'),
    ('ok','OK'),
    ('or','OR'),
    ('pa','PA'),
    ('ri','RI'),
    ('sc','SC'),
    ('sd','SD'),
    ('tn','TN'),
    ('tx','TX'),
    ('ut','UT'),
    ('vt','VT'),
    ('va','VA'),
    ('wa','WA'),
    ('wv','WV'),
    ('wi','WI'),
    ('wy','WY'),
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    address_1 = models.CharField(max_length=100)
    address_2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=2, choices=STATE_CHOICES)
    zipcode = models.CharField(max_length=9, validators=[MinLengthValidator(5)])

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

sd_app/forms.py
import datetime
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import UserProfile, Transaction

# Widget to display a dropdown menu of states for transaction form.
class DateInput(forms.DateInput):
    input_type = 'date'

# Creates a form for the user to register a new user account.
class NewUserForm(UserCreationForm):
    #email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        labels = {  'username': 'Username', 'password1': 'Password', 
                    'password2': 'Confirm Password'}    
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)		
        if commit:
            user.save()
        return user

# Create a form for the user to update their profile information.
class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile 
        fields = ('full_name', 'address_1', 'address_2', 'city', 'state', 'zipcode')      

class BuyForm(forms.ModelForm):
   
    def clean(self):
        cleaned_data = super(BuyForm, self).clean()
        reservation_date = cleaned_data['reservation_date']
        converted_date = datetime.datetime.strptime(reservation_date, '%Y-%m-%d').date()
        # print("today: ", datetime.date.today())
        # print("reservation_date: ", reservation_date)
        # print("converted_date: ", converted_date)
        if converted_date < datetime.date.today():
            raise forms.ValidationError("Reservation date must be in the future.")
        
        return cleaned_data

    class Meta:
        model = Transaction
        fields = ('number_of_people', 'reservation_date', 'reservation_time', 'user_phone_number', 'user_email', 'preferred_payment_method')
        widgets = {'reservation_date': DateInput()}

sd_app/views.py
from django.shortcuts import render, redirect

from django.views.generic import TemplateView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import NewUserForm, ProfileForm, BuyForm

from .models import Transaction, UserProfile

class PricingModule:
    pass

class LoginPageView(TemplateView):
    template_name = 'sd_app/login.html'

class HomePageView(TemplateView):
    template_name = 'sd_app/home.html'
    #print("\t\tHome page rendered\n")

@login_required
def profilePage(request):
    ''' Display user profile information and allow them to update profile information.
        Display transaction history of User.'''    
    if request.method == 'POST': # Form has been submitted
        #print("\t\tPOST request received\n")
        #user_form = NewUserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.userprofile)
        if profile_form.is_valid():
            #print("\t\tForms are valid\n")
            #user_form.save()
            profile_form.save()            
            return redirect('sd_app:profile')
    else: # GET request, display current information
        profile_form = ProfileForm(instance=request.user.userprofile)
    #     print("\t\tGET request received\n") 
    context = {'profile_form': profile_form}    
    return render(request, 'sd_app/profile.html', context)    

def registerPage(request):
    # '''Prompt user to register, after registering redirect to login page'''
    # return render(request, 'registration/register.html')  
    #print("\t\tRegister page view call\n")
    if request.method != 'POST':
        # Display a blank registration form.
        #print("\t\tGET request received\n")
        form = NewUserForm()
    if request.method == "POST":
        #print("\t\tPOST request received\n")
        form = NewUserForm(data=request.POST)
        if form.is_valid():
            #print("\t\tForm is valid\n")
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("sd_app:home")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    
    return render (request=request, template_name="registration/register.html", context={"register_form":form})

@login_required
def buyPage(request):
    '''Prompt user to buy, after buying refresh page.
    Display total price of transaction.
    Link to logout.'''
    addressItems = UserProfile.objects.filter(user=request.user)
    if request.method != 'POST': 
        #print("\t\tbuyPage: GET request received\n")
        form = BuyForm()
    elif 'submit' in request.POST: # POST
        #print("\t\tbuyPage: POST request received\n")
        form = BuyForm(data=request.POST)
        if form.is_valid():
            #print("\n\t\tbuyPage Submit: Form is valid\n")
            #form.initial['user_id'] = request.user.id
            new_purchase = form.save(commit=False)
            new_purchase.user = request.user
            #calculate the price and total amount
            #amount = int(request.POST['gallons_requested'])
            #location = addressItems[0].state
            count = Transaction.objects.filter(user=request.user).count()
            if count != 0:
                history = 1
            else:
                history = 0
            #save the data to database
            new_purchase.address_1 = addressItems[0].address_1
            new_purchase.address_2 = addressItems[0].address_2
            new_purchase.city = addressItems[0].city
            new_purchase.state = addressItems[0].state
            new_purchase.zipcode = addressItems[0].zipcode
            new_purchase.save()
            #return redirect('sd_app:buy')
        #print("\n\t\tbuyPage Submit: Form is invalid\n")

    context = {'buy_form': form, 'address_1' : addressItems[0].address_1, 'address_2' : addressItems[0].address_2, 'city' : addressItems[0].city, 'state' : addressItems[0].state, 'zipcode' : addressItems[0].zipcode}
    return render(request, 'sd_app/buy.html', context)

@login_required
def purchaseHistoryPage(request):
    purchases = Transaction.objects.filter(user=request.user)
    #context = {'purchases': purchases}    
    return render(request, 'sd_app/purchase_history.html', {'purchases': purchases})

sd_app/templates/sd_app/base.html
<!-- Content shared across all pages in website.-->
<p>
  <a href="{% url 'sd_app:home' %}">Home Page</a>
</p>

{% block content %}
{% endblock content %}

sd_app/templates/sd_app/buy.html
{% extends "sd_app/base.html" %}
    
{% block content %}
<h2> Reservation Form</h2>
<body>  
    <form method="POST" action="{% url 'sd_app:buy' %}">
        {% csrf_token %}
        {{ buy_form.as_p }}
        <p>User Address: {{ address_1 }}, {{ address_2 }}, {{ city }}, {{ state }} {{ zipcode }} </p>
        <button type="submit" name="submit">Submit Reservation</button>
       
    </form>
 
</body>
    
{% endblock content %}

sd_app/templates/sd_app/home.html
<h1>Cougar Steakhouse</h1>

{% if user.is_authenticated %}
    <p>Hello {{user.username}}</p>
    <p>
        <a href="{% url 'sd_app:profile' %}">Update Profile</a>
    </br>
    </br>
        <a href="{% url 'sd_app:buy' %}">Make a Reservation</a>
    </br>
    </br>
        <a href="{% url 'sd_app:purchase_history' %}">Upcoming Reservations</a>
    <br/>
    <br/>
        <a href="{% url 'logout' %}">Logout</a>
    </p>
{% else %}
    <a href="{% url 'login' %}">Login</a>
</br>
</br>
</br>
    <a href="{% url 'sd_app:register' %}">Register</a>
{% endif %}

sd_app/templates/sd_app/profile.html
<!DOCTYPE html>
{% extends "sd_app/base.html" %}

{% block content %}
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h2>Profile</h2>    
    <h3>{{ user.username }}</h3>
    <form action="{% url 'sd_app:profile' %}" method="POST">
        {% csrf_token %}        
        {{ profile_form.as_p }}
        <button class="btn btn-primary" type="submit">Save / Update Profile</button>
    </form>
    <br>
    
</body>
</html>
{% endblock %}

sd_app/templates/sd_app/purchase_history.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
    {% extends "sd_app/base.html" %}

    {% block content %}
    <style>
        table {
            border-collapse: collapse;            
        }
        
    </style>
<body>
    <h3>Logged in as: {{ user.username }}</h3>
    <h2>Upcoming Reservations</h2>

    <table border="1">
        <tr>
            <td>&nbsp;Number of People&nbsp;</td>
            <td>&nbsp;Reservation Date&nbsp;</td>
            <td>&nbsp;Reservation Time&nbsp;</td>
            <td>&nbsp;Preferred Payment Method&nbsp;</td>
            <td>&nbsp;User Phone Number&nbsp;</td>
            <td>&nbsp;User Email&nbsp;</td>
            <td>&nbsp;User Address 1&nbsp;</td>
            <td>&nbsp;User Address 2&nbsp;</td>
            <td>&nbsp;User City&nbsp;</td>
            <td>&nbsp;User State&nbsp;</td>
            <td>&nbsp;User Zipcode&nbsp;</td>

        </tr>
        {% for item in purchases %}
        <tr>
            <td>{{ item.number_of_people }}</td>
            <td>{{ item.reservation_date }}</td>
            <td> {{ item.reservation_time }}</td>
            <td>{{ item.preferred_payment_method }}</td>
            <td> {{ item.user_phone_number }}</td>
            <td> {{ item.user_email }}</td>
            <td> {{ item.address_1 }}</td>
            <td> {{ item.address_2 }}</td>
            <td> {{ item.city }}</td>
            <td> {{ item.state }}</td>
            <td> {{ item.zipcode }}</td>

        </tr>
        {% endfor %}
    </table>

</body>
    {% endblock content %}

</html>